(
    SELECTING_STORE,
    ENTERING_GROSS_TOTAL,
    ENTERING_RETAIL_TOTAL,
    ENTERING_ACQUIRING_TOTAL,
    ENTERING_CASHBOX_TOTAL,
    CONFIRMING_REPORT,
    ADMIN_MENU,
    ADMIN_ADD_STORE,
    ADMIN_SET_PLANS_STORE,
    ADMIN_SET_PLANS_VALUE,
    ADMIN_SET_CHAT_STORE,
    ADMIN_SET_CHAT_VALUE,
) = range(12)
