(
    SELECTING_STORE,
    ENTERING_GROSS_TOTAL,
    ENTERING_RETAIL_TOTAL,
    ENTERING_ACQUIRING_TOTAL,
    ENTERING_IM_ORDERS,
    ENTERING_CASHBOX_TOTAL,
    CONFIRMING_REPORT,

    ADMIN_MENU,
    ADMIN_ADD_STORE,
    ADMIN_SET_PLANS_STORE,
    ADMIN_SET_PLANS_VALUE,
    ADMIN_SET_CHAT_STORE,
    ADMIN_SET_CHAT_VALUE,

    SETUP_STORE_NAME,
    SETUP_DAILY_PLAN,
    SETUP_MONTHLY_ACQUIRING_PLAN,
    SETUP_ACQUIRING_BASE,
    SETUP_REPORT_TIME,
    SETUP_REPORT_CHAT_ID,
    SETUP_BOSS_ID,
    SETUP_CONFIRM,

    INVITE_MENU,

    SET_FULL_REPORT_CHAT_STORE,
    SET_FULL_REPORT_CHAT_VALUE,

    STATS_SUB_STORE,
    STATS_SUB_TARGET,
    STATS_SUB_CHAT_ID,
    STATS_SUB_PERIOD,
    STATS_SUB_TIME,
    CONFIRMING_CASHBOX_REPEAT,
) = range(30)
